<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\SnagList.Application\SnagList.Application.csproj" />
    <ProjectReference Include="..\SnagList.Infrastructure\SnagList.Infrastructure.csproj" />
    <ProjectReference Include="..\SnagList.Authorization\SnagList.Authorization.csproj" />
    <ProjectReference Include="..\SnagList.Api.Auth.Local\SnagList.Api.Auth.Local.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol.AspNetCore" Version="2.2.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
